"""Compatibility helpers for OpenAPI generated by pinned ADK releases."""

from __future__ import annotations

import hashlib
from collections import defaultdict

from fastapi import FastAPI
from fastapi.routing import APIRoute


def _emitted_operation_id(route: APIRoute) -> str:
    """Return the operation ID FastAPI will emit for a route."""
    return route.operation_id or route.unique_id


def _route_sort_key(route: APIRoute) -> tuple[str, tuple[str, ...], str]:
    """Return a registration-order-independent route key."""
    return (
        route.path_format,
        tuple(sorted(route.methods)),
        route.name,
    )


def _derived_operation_id(existing_id: str, route: APIRoute) -> str:
    """Derive a stable ID from the route path and all documented methods."""
    methods = tuple(sorted(route.methods))
    descriptor = "\0".join((route.path_format, *methods))
    digest = hashlib.sha256(descriptor.encode()).hexdigest()[:32]
    method_label = "_".join(methods).lower()
    return f"{existing_id}__{method_label}_{digest}"


def ensure_unique_operation_ids(app: FastAPI) -> int:
    """Resolve only duplicate OpenAPI IDs created by ADK 1.36.2.

    ADK 1.36.2 constructs its own ``FastAPI`` instance and does not expose
    FastAPI's ``generate_unique_id_function`` constructor argument. Applying
    explicit IDs after all routes are registered is therefore a compatibility
    workaround. Once ADK emits unique IDs itself, this function is a no-op and
    can be removed.

    Returns:
        The number of routes whose explicit operation ID was changed.
    """
    routes = [
        route
        for route in app.routes
        if isinstance(route, APIRoute) and route.include_in_schema
    ]
    routes_by_id: dict[str, list[APIRoute]] = defaultdict(list)
    for route in routes:
        routes_by_id[_emitted_operation_id(route)].append(route)

    reserved_ids = set(routes_by_id)
    updates: list[tuple[APIRoute, str]] = []
    for existing_id, duplicate_routes in sorted(routes_by_id.items()):
        if len(duplicate_routes) < 2:
            continue

        ordered_routes = sorted(duplicate_routes, key=_route_sort_key)
        for route in ordered_routes[1:]:
            base_candidate = _derived_operation_id(existing_id, route)
            candidate = base_candidate
            suffix = 2
            while candidate in reserved_ids:
                candidate = f"{base_candidate}_{suffix}"
                suffix += 1
            reserved_ids.add(candidate)
            updates.append((route, candidate))

    for route, operation_id in updates:
        route.operation_id = operation_id

    if updates:
        app.openapi_schema = None
    return len(updates)
